repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
        args: ['--recursive']
      - id: terraform_docs
      - id: terraform_tflint
        args:
          - '--args=--deep'
      - id: terraform_tfsec
      - id: checkov
        args: ['--skip-check', 'CKV_AWS_20', '--framework', 'terraform']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-json
      - id: check-added-large-files
